#!/usr/bin/bash
PIPE_FOR="SM"
PIPE_DESC80="MMY3(+4?) -scrub +wave +hpfilter.099 +reg:m,wm,csf,alldervs"
PIPE_DESC="
This pipeline processes rest data for Scott's MEG subjects
using Multiband Data (using fieldmaps and ref&func from hdr/img )
scrubbing no
wavlet    yes
filter    filter anyting lower than .009 (give 3dBandpass 999 > Nysquist => highpass only)
regs      6motion,wm,csf,d6motion,dwm,dcsf 
"
PIPE_DEPENDS=("MHT1_2mm" "cpFM" )
PIPE_VERSION="20151215"
FINALOUT=( ".preprocessfunctional_complete" )

function check_complete {
 wantonlyoneid $@ || return 1
 has_finalout  $1 || return 1
 return 0
}

function run_pipeline {
 id="$1"
 [ -z "$id" ] && warn "$FUNCNAME: no id given" && return 1
 [ -z "$FM_CFG" ] && warn "$FUNCNAME: no FM_CFG in env!" && return 1


 [ ! -d "$id" ] && mkdir $id
 cd $id

 # find inputs
 t2=$(subj_t2 $id)
 ref=$(subj_ref $id)
 read mag phase < <(find_fm $id)
 read bet warp  < <(find_t1final $id)
 for v in t2 ref mag phase bet warp; do
   [ -z "${!v}" ] && warn "# cannot find $v for $id" && return 1
 done

 # create nii.gz from analize fmt (img hdr)
 [ ! -r functional.nii.gz ]     && 3dcopy $t2  functional.nii.gz
 [ ! -r functional_ref.nii.gz ] && 3dcopy $ref functional_ref.nii.gz
 [ ! -r functional.nii.gz -o ! -r functional_ref.nii.gz ] && 
    warn "# failed to copy analyse ($t2 and $ref) into $(pwd)" && return 1


 preprocessFunctional -4d 'functional.nii.gz' \
   -func_refimg functional_ref.nii.gz \
   -tr $FUNCTR -slice_acquisition $FUNCSLICEACQ \
   -mprage_bet $bet -warpcoef $warp \
   -4d_slice_motion -wavelet_despike  \
   -rescaling_method 10000_globalmedian \
   -template_brain MNI_3mm    \
   -fm_cfg $FM_CFG \
   -fm_phase "$phase"  -fm_magnitude "$mag" \
   -nuisance_regression 6motion,wm,csf,d6motion,dwm,dcsf \
   -bandpass_filter 0.009 9999 \
   -no_hp #default is 80, maybe want 125s (.008)

   # these options are taken from the dicoms, hopefully
   #-tr 1.5 -slice_acquisition seqasc  \

 check_complete $id || return 1

 return 0
}

