#!/usr/bin/bash
PIPE_DESC80="preprocessDistortion wrapper for fieldmaps"
PIPE_DESC="
Run the fieldmap portion of preprocessFunctional
with preprocessDistortion. 
also see MHFM
"
PIPE_DEPENDS=""
PIPE_VERSION="20171114"
FINALOUT=(".preprocessDistortion_complete" "unwarp/FM_UD_fmap_mag.nii.gz"  "unwarp/FM_UD_fmap.nii.gz")

function check_complete {
 wantonlyoneid $@ || return 1
 has_finalout  $1 || return 1
 return 0
}

# run from $PPSUBJSDIR 
function run_pipeline {
 # check id input and make/cd into id dir
 id="$1"
 wantonlyoneid $id || return 1
 [ ! -d "$id" ] && mkdir $id
 cd $id
 [ -z $FM_CFG ] && warn "pipeline requires FM_CFG. Not provided by source!" && return 1

 # find the t1dir with MRs in it
 read mrmag mrphase < <(subj_fm $id)
 [ -z "$mrmag" -o -z "$mrphase" ] && warn "could not find fm mag and phase for $id: source pipeline and source; 'subj_fm $id'" && return 1

 preprocessDistortion -phasedir $mrphase -magdir $mrmag -fm_cfg $FM_CFG


 # exit successfuly
 return 0
}

# vim: set tabstop=7:
