#!/usr/bin/env bash
# 80 char description
SOURCE_DESC80="7T brain mechanisms R01 rest"

SUBJECTS_DIR="/DNE/" # no freesurfer currently
DICOM_PAT="*IMA" # here, but do not use -- have "bids"

FUNCTR="2.18" # see subj_tr() 2.18 only valid for first few
FUNCSLICEACQ="3d" # no slice acq

MRROOT="/Volumes/Hera/Raw/BIDS/7TBrainMech/rawlinks/"
BIDSROOT="/Volumes/Hera/Raw/BIDS/7TBrainMech/"

# There is no fieldmap
FM_CFG=""

function list_all {
 ls $BIDSROOT/sub-*/*/func/*task-MGS*bold.nii.gz | 
 perl -lne 'print "${1}_$2" if m:sub-(\d+)/(\d+)/:' | sort -u
}

function subj_tr {
  ld8="$1"; shift
  trdb=/Volumes/Hera/Projects/7TBrainMech/scripts/mri/txt/task_trs.txt
  tr=$(grep sub-"${ld8/_/\/}" $trdb |cut -d' ' -f2 |sed 1q)
  [ -n "$tr" ] && echo "$tr" || echo $FUNCTR
}

function subj_t1 {
 wantonlyoneid $@ || return 1
 find $(ld8_to_bids $1)/anat/ -iname '*T1w.nii.gz' | sed -n '$p'
}

function subj_t2s {
   # /Volumes/Hera/Raw/BIDS/7TBrainMech/sub-11823/20210122/func/sub-11823_task-MGS_run-01_bold.nii.gz      01
   # /Volumes/Hera/Raw/BIDS/7TBrainMech/sub-11863/20210225/func/sub-11863_task-mgsshort2_run-03_bold.nii.gz        03_2
 wantonlyoneid $@ || return 1
 find $(ld8_to_bids $1)/func/ -iname '*MGS*.nii.gz'  | 
    perl -lne 'chomp; print "$_\t$4$3$2" if m/(short(\d+)(_))?run-(\d+)/;'
 return 0
}
subj_t2(){
   echo "ERROR: looking for only one subj_t2 but should use subj_t2s -- there are 3 runs (or as of 20210301, 6: 3x2)!" >&2
 return 1
 #subj_t2s $@
}


function subj_physio {
 wantonlyoneid $@ || return 1
 return 0
}
