#!/usr/bin/env bash
# 80 char description
SOURCE_DESC80="7T brain mechanisms R01 rest"

SUBJECTS_DIR="/DNE/" # no freesurfer currently
DICOM_PAT="*IMA" # here, but do not use -- have "bids"

FUNCTR="2.18" 
FUNCSLICEACQ="3d" # no slice acq

MRROOT="/Volumes/Hera/Raw/MRprojects/7TR01/"
BIDSROOT="/Volumes/Hera/Raw/BIDS/7TBrainMech/"

# There is no fieldmap
FM_CFG=""

function list_all {
 ls $BIDSROOT/sub-*/*/func/*task-rest_*bold.nii.gz | 
 perl -lne 'print "${1}_$2" if m:sub-(\d+)/(\d+)/:'
}



function subj_t1 {
 wantonlyoneid $@ || return 1
 find $(ld8_to_bids $1)/anat/ -iname '*T1w.nii.gz' | sed -n '$p'
}

function subj_t2s {
 wantonlyoneid $@ || return 1
 find $(ld8_to_bids $1)/func/ -iname '*rest*.nii.gz' | sed -n '$p'
 return 0
}
subj_t2(){
 subj_t2s $@
}


function subj_physio {
 wantonlyoneid $@ || return 1
 return 0
}
