#!/usr/bin/env bash
# 80 char description
SOURCE_DESC80="7T brain mechanisms R01 rest"

SUBJECTS_DIR="/DNE/" # no freesurfer currently
DICOM_PAT="*IMA" # here, but do not use -- have "bids"

FUNCTR="2.18" 
FUNCSLICEACQ="3d" # no slice acq

MRROOT="/Volumes/Hera/Raw/BIDS/7TBrainMech/rawlinks/"
BIDSROOT="/Volumes/Hera/Raw/BIDS/7TBrainMech/"

# There is no fieldmap
FM_CFG=""

function list_all {
 ls $BIDSROOT/sub-*/*/func/*task-MGS_*bold.nii.gz | 
 perl -lne 'print "${1}_$2" if m:sub-(\d+)/(\d+)/:' | sort -u
}



function subj_t1 {
 wantonlyoneid $@ || return 1
 find $(ld8_to_bids $1)/anat/ -iname '*T1w.nii.gz' | sed -n '$p'
}

function subj_t2s {
 wantonlyoneid $@ || return 1
 find $(ld8_to_bids $1)/func/ -iname '*MGS*.nii.gz'  | 
 perl -lne 'chomp; print "$_\t$1" if m/run-(\d+)/;'
 return 0
}
subj_t2(){
 echo "ERROR: looking for only one subj_t2 but should use subj_t2s -- there are 3 runs!"
 return 1
 #subj_t2s $@
}


function subj_physio {
 wantonlyoneid $@ || return 1
 return 0
}
