#!/usr/bin/env bash
SOURCE_DESC80="cog long task"
# source is not the actual source
# see /Volumes/Hera/preproc/cog_task/rest_spikemin/fakeit.bash
# which pulls from /Volumes/Phillips/CogRest/subjs/*/preproc (/rest_[1-4]/tm_rest_[1-4].nii.gz


FUNCTR="1.5"
FUNCSLICEACQ="interleaved"
TEMPLATE_RES=MNI_2.3mm 
SMOOTH_KERNEL=5

# no raw data, only niftis
MRROOT=""  DICOM_PAT=""
# but do have t1 dicoms
_MRT1NII=/Volumes/Hera/preproc/cog_task/MHT1_2mm
_MRT2SNII=/Volumes/Hera/preproc/cog_task/rest_spikemin
# no fieldmap
NO_FM=1
FM_CFG="" FMNMAG= FMNPHS=
# no slicetiming
SLICESETTINGSFILE="" TIMING1D="" SUBJECTS_DIR=""


# find subjects by listing who has mprages preprocessed
function list_all {
 ls -d $_MRT1NII/1*_2*/ | perl -F/ -alne 'print $F[$#F]'
}

function subj_t1 {
 wantonlyoneid $@ || return 1
 #file_exists_test "$SUBJECTS_DIR/$1/mri/T1.mgz"
 echo $_MRT1NII/$1/mprage.nii.gz
}


# return nii.gz and task name (taskname=1-4)
# 
function subj_t2s {
 wantonlyoneid $@ || return 1
 ld=$1
 maindir=$_MRT2SNII/$1
 ls $maindir/[1-4]/tm_func.nii.gz |
  sed "s;^$maindir/\(.*\)/tm_func.nii.gz$;& \1;"
}
subj_t2() { subj_t2s $@||return 1;}

# will take directory instead of lunaid
function subj_ref {
 return 1
}


function subj_physio {
 return 1
 wantonlyoneid $@ || return 1
}

function subj_fm {
 return 1
 wantonlyoneid $@ || return 1
}

