#!/usr/bin/env bash
SOURCE_DESC80="Multimodal Year 1&2, not multiband, no fieldmaps"
  
SUBJECTS_DIR="/data/Luna1/MM/FS_Subjects/"
DICOM_PAT="MR*"


FUNCTR="2"
FUNCSLICEACQ="seqasc"

MRROOT="/data/Luna1/Raw/MultiModal/"

function list_all {
 echo "11075_20130625"
}

# given an id, pattern, and dicomcount
# echo the 1 directory that matches or return error
function subj_t1 {
 wantonlyoneid $@ || return 1
 subj_mr_pat $MRROOT/$1 'axial_mprage*' 192 || return 1
 return 0
}

function subj_t2 {
 wantonlyoneid $@ || return 1
 subj_mr_pat $MRROOT/$1 '*rest*' 150 || return 1
 return 0
}

## no ref,fm, or physio
function subj_ref {
 wantonlyoneid $@ || return 1
 echo ""
 return 0
}
function subj_fm {
 wantonlyoneid $@ || return 1
 echo ""
 return 0
}

function subj_physio {
 wantonlyoneid $@ || return 1
 echo ""
 return 0
}
