#!/usr/bin/env bash
# 80 char description
SOURCE_DESC80="NCANDA full dataset baseline - year2"

SUBJECTS_DIR="/DNE/" # no freesurfer currently
DICOM_PAT="*NONE" # no dicoms, comes from dataset

FUNCTR="2.2" 
FUNCSLICEACQ="??" # no slice acq have both GE and seiemns (interlaved)
TEMPLATE_RES=MNI_3mm 
SMOOTH_KERNEL=5

MRROOT="/DNE/"
NIIROOT="/Volumes/Hera/Raw/Datasets/NCANDA/"
DBFILE="$NIIROOT/id_t1_epi.tsv"

# TODO: make config for ncanda 
FM_CFG=""
_mkncandadb() {
 # have 3 visits: find all that have both t1 and rest and
 #  create session id like 'ncandaid_year' where baseline = year 0 to so 1y and 2y match raw directory names
 #  /Volumes/Hera/Raw/Datasets/NCANDA/baseline/NCANDA_IMAGEDATA_00012_V01/cases/NCANDA_S00095/standard/baseline/structural/native/t1.nii.gz
 #  /Volumes/Hera/Raw/Datasets/NCANDA/followup_1y/NCANDA_RELEASE_1Y_STRUCTURAL_IMAGES_V01/cases/NCANDA_S01009/standard/followup_1y/structural/native/t1.nii.gz
 [ -r $DBFILE -a -z "$REDODBFILE" ] && return 0
 find $NIIROOT -name 't1.nii.gz' -path '*/structural/native/*' | 
  perl -MFile::Find -lne '
     if(m:NCANDA_(S\d+)/.*/(baseline|followup_\dy)/:){
       $id=$1; $y=$2;$t1=$_;
       $y=~s/baseline/0/;$y=~s/followup_(\d)y/\1/;
       $a{"${id}_${y}"}=$t1;
    }END{
      print "$_\t$a{$_}" for (sort keys %a);
    }' |
  while read id t1; do
    t2=$(dirname $t1)
    t2=${t2/NCANDA_*\/case/*/case}  
    t2=${t2/structural\//restingstate/}  
    t2=$(find $t2 -name 'bold-001.nii.gz' || echo "")
    [ -n "$t2" ] && echo -e "$id\t$t1\t$t2" || :
  done |tee  $DBFILE
}

function list_all {
   # just the ids from DBFILE
   _mkncandadb
   cut -f1 $DBFILE
}



function subj_t1 {
 wantonlyoneid $@ || return 1
 _mkncandadb
 awk -v id="$1" '($1==id){print $2; quit}' $DBFILE
}

function subj_t2 {
 wantonlyoneid $@ || return 1
 local t2=$(awk -v id="$1" '($1==id){print $3; quit}' $DBFILE)
 [ -z "$t2" ] && echo "$FUNCNAME: no id $1" >&2 && return 1
 [ ! -r functional.nii.gz ] && 3dTcat -prefix functional.nii.gz -tr $FUNCTR ${t2/-001/*}
 [ -r functional.nii.gz ] && echo functional.nii.gz || return 1
 return 0
}


function subj_physio {
 wantonlyoneid $@ || return 1
 return 0
}
