#!/usr/bin/env bash

ncandasrc="$(dirname ${BASH_SOURCE})/ncanda"
[ -z "$ncandasrc" -o ! -r "$ncandasrc"  ] && echo "cannot find '$ncandasrc'" >&2 && exit 1
source "$ncandasrc"

# 80 char description
SOURCE_DESC80="NCANDA GE"

scannerargs="-wavelet_threshold 100 -wavelet_m1000"

#DBFILE="$NIIROOT/id_t1_epi.tsv"
#DBSITE="$NIIROOT/id_site.tsv"
function list_all {
   # just the ids from DBFILE
   _mkncandadb
   _mkndcandasite
   #  547 A - S
   #  715 B - G
   #  700 C - G
   #  698 D - S
   # 1035 E - G
   egrep '(B|C|E)$' $DBSITE |
      cut -f1 |
      join -j1 - $DBFILE |
      cut -f1 -d' '
}
