#!/usr/bin/env bash

# use rac1 as a template
rac1file=$(dirname ${BASH_SOURCE})/petrest_rac1
[ ! -r $rac1file ] && echo "cannot find '$rac1file'" >&2 && exit 1
source $rac1file

SOURCE_DESC80="mMR DA PET first rest in session 2 (rac tracer)"

_PETEPISUFFIX=racrest2

# look up e*rest* directories from pet study in the mr protocol database
# select the last rest with more than 200 dicoms for ids that have a B in them (only rac+dtbz people)
# only the last session and only where there are two sessions on the same day
_dbquery() {
 sqlite3 -separator $'\t' /Volumes/Zeus/mr_sqlite/db "
with 
 func_count as (
  select id,sessionname,count(*) as nfuncs 
  from mrinfo 
  where study like 'pet' and Name like '%BOLD_x%' and ndcm = 200 
  group by id,sessionname 
 ),
 all_pet_rest as (
  select patname,id,sessionname,count(*) as nrest, min(seqno) as firstrest,  max(seqno) as lastrest
  from mrinfo 
  where study like 'pet' and Name like '%BOLD_rest%'  and ndcm = 320 
  group by id,patname,sessionname
 ),
 rest_task_count as (
 select ap.*,nfuncs
   from all_pet_rest as ap
   left join func_count as fc
    on ap.id=fc.id  and ap.sessionname = fc.sessionname 
 ),
 -- fieldmap: match phase and magnitude
 fm_mag as (
 select patname,id,sessionname,seqno,dir
  from mrinfo 
  where study like 'pet' and Name like '%gre_field_mapping' and ndcm = 90
 ),
 fm_phase as (
 select patname,id,sessionname,seqno,dir
  from mrinfo 
  where study like 'pet' and Name like '%gre_field_mapping' and ndcm = 45
 ), 
 fm_match as (
  select m.patname,m.id,m.sessionname, m.dir as fmmag,p.dir as fmphase, m.seqno as magseqno ,p.seqno as phaseseqno
  from fm_mag as m 
  inner join fm_phase as p on m.id=p.id and m.patname=p.patname and m.sessionname=p.sessionname
  where m.seqno + 1 = p.seqno 
 ),
 -- pick the rest we want
 rest_pick as (
 select substr(mi.patname,1,14) as ld8, 
  rtc.sessionname, mi.dir,mi.seqno, nrest
  from rest_task_count as rtc 
  join mrinfo as mi on rtc.id=mi.id and mi.sessionname = rtc.sessionname
   -- LOOK HERE: determine which rest we want  
   and mi.seqno=rtc.lastrest
 where
    nfuncs is not null
    and nrest = 2  
),
-- put rest and fm together
fm_rest as (
 select abs(seqno - magseqno) as diff, * from rest_pick as rp 
 join fm_match as fm on  rp.sessionname=fm.sessionname
 order by ld8,diff
),
-- find the closest fm to the rest
best_match_no as (
 select sessionname, min(diff) as closestdiff from fm_rest group by sessionname
)
-- give lunaid rest and fm dirs: mag is 2x as large (mag1,mag2) and before phase
select ld8,dir as restdir,fmmag,fmphase,diff 
  from fm_rest 
  join best_match_no on closestdiff=diff and fm_rest.sessionname = best_match_no.sessionname
";
}

