#!/usr/bin/env bash
SOURCE_DESC80="DESC in 80 chars"

SUBJECTS_DIR="/DNE/"
DICOM_PAT="MR*"

FUNCTR="1"
FUNCSLICEACQ="seqasc"

MRROOT="/Volumes/Phillips/Raw/MRprojects/P5Sz/"

# which field map config settings 
FM_CFG=clock


function list_all {
}

function subj_t1 {
 wantonlyoneid $@ || return 1
 file_exists_test "$SUBJECTS_DIR/$1/mri/T1.mgz"
}

function subj_MRT1 {
 wantonlyoneid $@ || return 1
 #subj_mr_pat $MRROOT/$1 'axial_mprage_256x208*' 176 || return 1
}

# segemention mask from freesurfer
function subj_FS_aseg {
 wantonlyoneid $@ || return 1
 file_exists_test "$SUBJECTS_DIR/$1/mri/aseg.mgz"
}

function subj_t2 {
 wantonlyoneid $@ || return 1
}
function subj_ref {
 wantonlyoneid $@ || return 1
}
function subj_physio {
 wantonlyoneid $@ || return 1
}
function subj_fm {
 wantonlyoneid $@ || return 1

 local path=($MRROOT/*/$1)
 warn "$FUNCNAME: looking for ${path[@]}"

 [ ${#path[@]} -gt 1 ] && warn "$FUNCNAMME: $1 has too many possible paths (${#path[@]}): ${path[@]}" && return 1

 mag=$(subj_mr_pat $path 'gre_field_*' 120)
 [ -z "$mag" ] && return 1
 phase=$(subj_mr_pat $path 'gre_field_*' 60)
 [ -z "$phase" ] && return 1
 echo "$mag $phase"
}
